services:
  - type: web
    name: pos-mocha-fullstack
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      # Install and build frontend
      npm ci
      RENDER=true npm run build:render
      # Install and build backend
      cd server
      npm ci
      npm run build
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
    autoDeploy: false