services:
  - type: web
    name: maria-havens-pos-frontend
    env: node
    buildCommand: npm install && VITE_API_URL=https://mariahavensbackend.onrender.com npm run build
    staticPublishPath: dist/client
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: VITE_API_URL
        value: https://mariahavensbackend.onrender.com
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html