services:
  - type: web
    name: pos-mocha-api
    env: node
    region: oregon
    plan: starter
    buildCommand: cd server && npm ci && npm run build
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://pos-mocha-frontend.onrender.com
    autoDeploy: false

  - type: web
    name: pos-mocha-frontend
    env: static
    region: oregon
    buildCommand: npm ci && npm run build:render
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    envVars:
      - key: RENDER
        value: "true"
      - key: VITE_API_URL
        fromService:
          type: web
          name: pos-mocha-api
          property: host
    autoDeploy: false