services:
  - type: web
    name: maria-havens-pos
    env: node
    buildCommand: npm install && npm run build && npm run build:backend
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
    autoDeploy: false